apiVersion: apps/v1
kind: Deployment
metadata:
  name: jerney-backend
  namespace: jerney
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jerney-backend
  template:
    metadata:
      labels:
        app: jerney-backend
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z jerney-db 5432; do
                sleep 3
              done
      containers:
        - name: backend
          image: rahuldev800/jeney-backend:latest   # ✅ updated image
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "jerney-db"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: jerney-db-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jerney-db-secret
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: jerney-db-secret
                  key: POSTGRES_DB
---
apiVersion: v1
kind: Service
metadata:
  name: jerney-backend
  namespace: jerney
spec:
  type: ClusterIP
  selector:
    app: jerney-backend
  ports:
    - port: 5000
      targetPort: 5000
