apiVersion: v1
kind: Secret
metadata:
  name: jerney-db-secret
  namespace: jerney
type: Opaque
data:
  POSTGRES_USER: amVybmV5X3VzZXI=
  POSTGRES_PASSWORD: amVybmV5X3Bhc3NfMjAyNg==
  POSTGRES_DB: amVybmV5X2Ri
